$ar_classdefs = [
    "T", # for cpp template
    "std",
    "SJournalKeys",
    "CBusinessObject",
    "PDAG",
    "TCHAR",
    "CBizEnv",
    "SBOString",
    "SBOErr",
    "DBD_Tables",
    "CManualDistributionRuleObject",
    "CWTAllCurBaseCalcParams",
    "CJDTWTInfo",
    "AccountsConstArray",
    "ObjectAbbrevsMap",
    "CBusinessService",
    "CJDTStornoExtraInfoCreator",
    "ArcDeletePrefs",
    "CJECompression",
    "ObjectWTaxInfo",
    "DBQRetrieveStatement",
    "CMatchData",
    "MONEY",
    "BPBalanceChangeLogDataArr",
    "FCRoundingStruct",
    "StdMap",
    "CostAccountingFieldMap",
    "bool",
    "AccountsArray",
    # pojdt.c
    "CPaymentDoc",
    # __DMBC_DAG.cpp
    "CSystemBusinessObject",
    "SBOXmlParser",
    "CDBMEnv",
    "CORE_BYTE",
    "DAG_RecordStatusList",
    "wchar_t",
    "DBM_ChangedColumn",
    "CReconUpgMgr",
    "CSystemMatchManager",
    "CCompanyInfo",
    "CItemMasterData",
    "MONEY_RoundRule",
    "IRoundingData",
    "PDBD_Cond",
    "PDBD_Upd",
    "BGSDataPtr",
    "TotalsPair",
    "CINVLineAgreementInfoMap"
    ]

$unusableType =[
    "export"
]