$ar_classdefs = [
    "T", # for cpp template
    "std",
    "SJournalKeys",
    "CBusinessObject",
    "PDAG",
    "TCHAR",
    "CBizEnv",
    "SBOString",
    "SBOErr",
    "DBD_Tables",
    "CManualDistributionRuleObject",
    "CWTAllCurBaseCalcParams",
    "CJDTWTInfo",
    "AccountsConstArray",
    "ObjectAbbrevsMap",
    "CBusinessService",
    "CJDTStornoExtraInfoCreator",
    "ArcDeletePrefs",
    "CJECompression",
    "ObjectWTaxInfo",
    "DBQRetrieveStatement",
    "CMatchData",
    "MONEY",
    "BPBalanceChangeLogDataArr",
    "FCRoundingStruct",
    "StdMap",
    "CostAccountingFieldMap",
    "bool",
    "AccountsArray",
    # pojdt.c
    "CPaymentDoc",
    # __DMBC_DAG.cpp
    "CSystemBusinessObject",
    "SBOXmlParser",
    "CDBMEnv",
    "CORE_BYTE",
    "DAG_RecordStatusList",
    "wchar_t",
    "DBM_ChangedColumn",
    "CReconUpgMgr",
    "CSystemMatchManager",
    "CCompanyInfo",
    "CItemMasterData",
    "MONEY_RoundRule",
    "IRoundingData",
    "PDBD_Cond",
    "PDBD_Upd",
    "BGSDataPtr",
    "TotalsPair",
    "CINVLineAgreementInfoMap",
    "Currency",
    "DocSubTypeStruct",
    "DBD_TablesList",
    "DBD_CondTables",
    "DBD_Conditions",
    "PDBD_Sort",
    "PDBD_Group",
    "PDBD_Res",
    "PDBD_Filter",
    "DBMCconnBase",
    "PDBD_Params",
    "DBM_PreparedStatementType",
    "DBMCSqlStatement",
    "DBM_CA",
    "DBM_BindType"
]

$unusableType =[
    "export"
]

#file don't include, all is downcased filename
$exclude_file=[
    "stdio",
    "stdio.h",
    "malloc.h",
    "windows.h",
    "sql.h",
    "sqlext.h",
    "__DBM.*\\.h",
    "__CORE_OS.h",
    "WinCrypt.h",
    "Assert.h"
]
    
