ERRMSG=["EOF expected",
"identifier expected",
"number expected",
"hexnumber expected",
"string1 expected",
"char1 expected",
"library expected",
"\"use\" expected",
"\";\" expected",
"\"load\" expected",
"\"package\" expected",
"\"/\" expected",
"\"inherit\" expected",
"\"<\" expected",
"\"class\" expected",
"\"{\" expected",
"\"}\" expected",
"\"static\" expected",
"\"my\" expected",
"\"function\" expected",
"\"var\" expected",
"\"mixed\" expected",
"\"short\" expected",
"\"int\" expected",
"\"long\" expected",
"\"float\" expected",
"\"unsigned\" expected",
"\"char\" expected",
"\"double\" expected",
"\"void\" expected",
"\"string\" expected",
"\"=\" expected",
"\",\" expected",
"\"[\" expected",
"\"]\" expected",
"\"(\" expected",
"\")\" expected",
"\"*\" expected",
"\"case\" expected",
"\":\" expected",
"\"default\" expected",
"\"break\" expected",
"\"continue\" expected",
"\"do\" expected",
"\"while\" expected",
"\"for\" expected",
"\"if\" expected",
"\"else\" expected",
"\"return\" expected",
"\"switch\" expected",
"\"||\" expected",
"\"&&\" expected",
"\"|\" expected",
"\"^\" expected",
"\"&\" expected",
"\"==\" expected",
"\"!=\" expected",
"\">\" expected",
"\"<=\" expected",
"\">=\" expected",
"\"<<\" expected",
"\">>\" expected",
"\"+\" expected",
"\"-\" expected",
"\"%\" expected",
"\"++\" expected",
"\"--\" expected",
"\".\" expected",
"\"->\" expected",
"\"::\" expected",
"\"##\" expected",
"\"new\" expected",
"\"$\" expected",
"\"*=\" expected",
"\"/=\" expected",
"\"%=\" expected",
"\"+=\" expected",
"\"-=\" expected",
"\"&=\" expected",
"\"^=\" expected",
"\"|=\" expected",
"\"<<=\" expected",
"\">>=\" expected",
"\"!\" expected",
"\"~\" expected",
"not expected",
"PreProcessor expected",
"unexpected symbol in C",
"unexpected symbol in Inheritance",
"unexpected symbol in Definition",
"unexpected symbol in Statements",
"unexpected symbol in StorageClass",
"unexpected symbol in Type",
"unexpected symbol in Type",
"unexpected symbol in Type",
"unexpected symbol in Type",
"unexpected symbol in Statement",
"unexpected symbol in Label",
"unexpected symbol in LocalDeclaration",
"unexpected symbol in LocalDeclaration",
"unexpected symbol in AssignmentOperator",
"unexpected symbol in EqualExp",
"unexpected symbol in RelationExp",
"unexpected symbol in ShiftExp",
"unexpected symbol in AddExp",
"unexpected symbol in MultExp",
"unexpected symbol in UnaryExp",
"unexpected symbol in UnaryExp",
"unexpected symbol in PostFixExp",
"unexpected symbol in PostFixExp",
"unexpected symbol in UnaryOperator",
"unexpected symbol in Primary",
"unexpected symbol in Primary",
"unexpected symbol in HashItem",
"Error in including file ",
"unknow type",
"unknown error "
]