class Jdt1 < ApplicationRecord
    
    def b1fields_array
        [
        {:name=>"BatchNum", :type=>"integer"},
        {:name=>"TransId", :type=>"integer"},
        {:name=>"BtfStatus", :type=>"string"},
        {:name=>"TransType", :type=>"string"},
        {:name=>"BaseRef", :type=>"string"},
        {:name=>"RefDate", :type=>"date"},
        {:name=>"Memo", :type=>"string"},
        {:name=>"Ref1", :type=>"string"},
        {:name=>"Ref2", :type=>"string"},
        {:name=>"CreatedBy", :type=>"integer"},
        {:name=>"LocTotal", :type=>"float"},
        {:name=>"FcTotal", :type=>"float"},
        {:name=>"SysTotal", :type=>"float"},
        {:name=>"TransCode", :type=>"string"},
        {:name=>"OrignCurr", :type=>"string"},
        {:name=>"TransRate", :type=>"float"},
        {:name=>"BtfLine", :type=>"integer"},
        {:name=>"TransCurr", :type=>"string"},
        {:name=>"Project", :type=>"string"},
        {:name=>"DueDate", :type=>"date"},
        {:name=>"TaxDate", :type=>"date"},
        {:name=>"PCAddition", :type=>"string"},
        {:name=>"FinncPriod", :type=>"integer"},
        {:name=>"DataSource", :type=>"string"},
        {:name=>"UpdateDate", :type=>"date"},
        {:name=>"CreateDate", :type=>"date"},
        {:name=>"UserSign", :type=>"integer"},
        {:name=>"UserSign2", :type=>"integer"},
        {:name=>"RefndRprt", :type=>"string"},
        {:name=>"LogInstanc", :type=>"integer"},
        {:name=>"ObjType", :type=>"string"},
        {:name=>"Indicator", :type=>"string"},
        {:name=>"AdjTran", :type=>"string"},
        {:name=>"RevSource", :type=>"string"},
        {:name=>"StornoDate", :type=>"date"},
        {:name=>"StornoToTr", :type=>"integer"},
        {:name=>"AutoStorno", :type=>"string"},
        {:name=>"Corisptivi", :type=>"string"},
        {:name=>"VatDate", :type=>"date"},
        {:name=>"StampTax", :type=>"string"},
        {:name=>"Series", :type=>"integer"},
        {:name=>"Number", :type=>"integer"},
        {:name=>"AutoVAT", :type=>"string"},
        {:name=>"DocSeries", :type=>"integer"},
        {:name=>"FolioPref", :type=>"string"},
        {:name=>"FolioNum", :type=>"integer"},
        {:name=>"CreateTime", :type=>"integer"},
        {:name=>"BlockDunn", :type=>"string"},
        {:name=>"ReportEU", :type=>"string"},
        {:name=>"Report347", :type=>"string"},
        {:name=>"Printed", :type=>"string"},
        {:name=>"DocType", :type=>"string"},
        {:name=>"AttNum", :type=>"integer"},
        {:name=>"GenRegNo", :type=>"string"},
        {:name=>"RG23APart2", :type=>"integer"},
        {:name=>"RG23CPart2", :type=>"integer"},
        {:name=>"MatType", :type=>"integer"},
        {:name=>"Creator", :type=>"string"},
        {:name=>"Approver", :type=>"string"},
        {:name=>"Location", :type=>"integer"},
        {:name=>"SeqCode", :type=>"integer"},
        {:name=>"Serial", :type=>"integer"},
        {:name=>"SeriesStr", :type=>"string"},
        {:name=>"SubStr", :type=>"string"},
        {:name=>"AutoWT", :type=>"string"},
        {:name=>"WTSum", :type=>"float"},
        {:name=>"WTSumSC", :type=>"float"},
        {:name=>"WTSumFC", :type=>"float"},
        {:name=>"WTApplied", :type=>"float"},
        {:name=>"WTAppliedS", :type=>"float"},
        {:name=>"WTAppliedF", :type=>"float"},
        {:name=>"BaseAmnt", :type=>"float"},
        {:name=>"BaseAmntSC", :type=>"float"},
        {:name=>"BaseAmntFC", :type=>"float"},
        {:name=>"BaseVtAt", :type=>"float"},
        {:name=>"BaseVtAtSC", :type=>"float"},
        {:name=>"BaseVtAtFC", :type=>"float"},
        {:name=>"VersionNum", :type=>"string"},
        {:name=>"BaseTrans", :type=>"integer"},
        {:name=>"ResidenNum", :type=>"string"},
        {:name=>"OperatCode", :type=>"string"},
        {:name=>"Ref3", :type=>"string"},
        {:name=>"SSIExmpt", :type=>"string"},
        {:name=>"SignMsg", :type=>"text"},
        {:name=>"SignDigest", :type=>"text"},
        {:name=>"CertifNum", :type=>"string"},
        {:name=>"KeyVersion", :type=>"integer"},
        {:name=>"CUP", :type=>"integer"},
        {:name=>"CIG", :type=>"integer"},
        {:name=>"SupplCode", :type=>"string"},
        {:name=>"SPSrcType", :type=>"integer"},
        {:name=>"SPSrcID", :type=>"integer"},
        {:name=>"SPSrcDLN", :type=>"integer"},
        {:name=>"DeferedTax", :type=>"string"},
        {:name=>"AgrNo", :type=>"integer"},
        {:name=>"SeqNum", :type=>"integer"},
    ]

    end
    
    def create
        # load json from file for testing
        
    end
end
