class CreateJdt2s < ActiveRecord::Migration[5.2]
  def change
    create_table :jdt2s do |t|
      t.integer :AbsEntry
      t.string :WTCode
      t.float :Rate
      t.float :TaxbleAmnt
      t.float :TxblAmntSC
      t.float :TxblAmntFC
      t.float :WTAmnt
      t.float :WTAmntSC
      t.float :WTAmntFC
      t.float :ApplAmnt
      t.float :ApplAmntSC
      t.float :ApplAmntFC
      t.string :Category
      t.string :Criteria
      t.string :Account
      t.string :Type
      t.string :RoundType
      t.string :BaseType
      t.integer :BaseAbsEnt
      t.integer :BaseLine
      t.integer :BaseNum
      t.integer :LineNum
      t.integer :BaseRef
      t.string :Status
      t.integer :TrgType
      t.integer :TrgAbsEntr
      t.integer :LogInstanc
      t.string :ObjType
      t.integer :Doc1LineNo
      t.string :WtLineType
      t.string :TxblCurr
      t.string :DtblCurr
      t.float :DtblRate
      t.float :txblRate
      t.float :DtblAmount
      t.string :TdsAcc
      t.string :SurAcc
      t.string :CessAcc
      t.string :HscAcc
      t.float :TdsRate
      t.float :SurRate
      t.float :CessRate
      t.float :HscRate
      t.float :TdsBAmt
      t.float :TdsBAmtSC
      t.float :TdsBAmtFC
      t.float :SurBAmt
      t.float :SurBAmtSC
      t.float :SurBAmtFC
      t.float :CessBAmt
      t.float :CessBAmtSC
      t.float :CessBAmtFC
      t.float :HscBAmt
      t.float :HscBAmtSC
      t.float :HscBAmtFC
      t.float :TdsAmnt
      t.float :TdsAmntSC
      t.float :TdsAmntFC
      t.float :SurAmnt
      t.float :SurAmntSC
      t.float :SurAmntFC
      t.float :CessAmnt
      t.float :CessAmntSC
      t.float :CessAmntFC
      t.float :HscAmnt
      t.float :HscAmntSC
      t.float :HscAmntFC
      t.float :TdsAppl
      t.float :TdsApplSC
      t.float :TdsApplFC
      t.float :SurAppl
      t.float :SurApplSC
      t.float :SurApplFC
      t.float :CessAppl
      t.float :CessApplSC
      t.float :CessApplFC
      t.float :HscAppl
      t.float :HscApplSC
      t.float :HscApplFC
      t.integer :BatchNum
      t.string :InCSTCode
      t.string :OutCSTCode

      t.timestamps
    end
  end
end
