# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2019_05_27_095740) do

  create_table "jdt1s", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
    t.integer "TransId"
    t.integer "Line_ID"
    t.string "Account"
    t.float "Debit"
    t.float "Credit"
    t.float "SYSCred"
    t.float "SYSDeb"
    t.float "FCDebit"
    t.float "FCCredit"
    t.string "FCCurrency"
    t.date "DueDate"
    t.integer "SourceID"
    t.integer "SourceLine"
    t.string "ShortName"
    t.integer "IntrnMatch"
    t.integer "ExtrMatch"
    t.string "ContraAct"
    t.string "LineMemo"
    t.string "Ref3Line"
    t.string "TransType"
    t.date "RefDate"
    t.date "Ref2Date"
    t.string "Ref1"
    t.string "Ref2"
    t.integer "CreatedBy"
    t.string "BaseRef"
    t.string "Project"
    t.string "TransCode"
    t.string "ProfitCode"
    t.date "TaxDate"
    t.float "SystemRate"
    t.date "MthDate"
    t.float "ToMthSum"
    t.integer "UserSign"
    t.integer "BatchNum"
    t.integer "FinncPriod"
    t.integer "RelTransId"
    t.integer "RelLineID"
    t.string "RelType"
    t.integer "LogInstanc"
    t.string "VatGroup"
    t.float "BaseSum"
    t.float "VatRate"
    t.string "Indicator"
    t.string "AdjTran"
    t.string "RevSource"
    t.string "ObjType"
    t.date "VatDate"
    t.string "PaymentRef"
    t.float "SYSBaseSum"
    t.integer "MultMatch"
    t.string "VatLine"
    t.float "VatAmount"
    t.float "SYSVatSum"
    t.string "Closed"
    t.float "GrossValue"
    t.integer "CheckAbs"
    t.integer "LineType"
    t.string "DebCred"
    t.integer "SequenceNr"
    t.string "StornoAcc"
    t.float "BalDueDeb"
    t.float "BalDueCred"
    t.float "BalFcDeb"
    t.float "BalFcCred"
    t.float "BalScDeb"
    t.float "BalScCred"
    t.string "IsNet"
    t.string "DunWizBlck"
    t.integer "DunnLevel"
    t.date "DunDate"
    t.integer "TaxType"
    t.string "TaxPostAcc"
    t.string "StaCode"
    t.integer "StaType"
    t.string "TaxCode"
    t.date "ValidFrom"
    t.float "GrossValFc"
    t.date "LvlUpdDate"
    t.string "OcrCode2"
    t.string "OcrCode3"
    t.string "OcrCode4"
    t.string "OcrCode5"
    t.integer "MIEntry"
    t.integer "MIVEntry"
    t.integer "ClsInTP"
    t.integer "CenVatCom"
    t.integer "MatType"
    t.integer "PstngType"
    t.date "ValidFrom2"
    t.date "ValidFrom3"
    t.date "ValidFrom4"
    t.date "ValidFrom5"
    t.integer "Location"
    t.string "WTaxCode"
    t.float "EquVatRate"
    t.float "EquVatSum"
    t.float "SYSEquSum"
    t.float "TotalVat"
    t.float "SYSTVat"
    t.string "WTLiable"
    t.string "WTLine"
    t.float "WTApplied"
    t.float "WTAppliedS"
    t.float "WTAppliedF"
    t.float "WTSum"
    t.float "WTSumFC"
    t.float "WTSumSC"
    t.string "PayBlock"
    t.integer "PayBlckRef"
    t.string "LicTradNum"
    t.integer "InterimTyp"
    t.integer "DprId"
    t.string "MatchRef"
    t.string "Ordered"
    t.integer "CUP"
    t.integer "CIG"
    t.integer "BPLId"
    t.string "BPLName"
    t.string "VatRegNum"
    t.string "SLEDGERF"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "jdt2s", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
    t.integer "AbsEntry"
    t.string "WTCode"
    t.float "Rate"
    t.float "TaxbleAmnt"
    t.float "TxblAmntSC"
    t.float "TxblAmntFC"
    t.float "WTAmnt"
    t.float "WTAmntSC"
    t.float "WTAmntFC"
    t.float "ApplAmnt"
    t.float "ApplAmntSC"
    t.float "ApplAmntFC"
    t.string "Category"
    t.string "Criteria"
    t.string "Account"
    t.string "Type"
    t.string "RoundType"
    t.string "BaseType"
    t.integer "BaseAbsEnt"
    t.integer "BaseLine"
    t.integer "BaseNum"
    t.integer "LineNum"
    t.integer "BaseRef"
    t.string "Status"
    t.integer "TrgType"
    t.integer "TrgAbsEntr"
    t.integer "LogInstanc"
    t.string "ObjType"
    t.integer "Doc1LineNo"
    t.string "WtLineType"
    t.string "TxblCurr"
    t.string "DtblCurr"
    t.float "DtblRate"
    t.float "txblRate"
    t.float "DtblAmount"
    t.string "TdsAcc"
    t.string "SurAcc"
    t.string "CessAcc"
    t.string "HscAcc"
    t.float "TdsRate"
    t.float "SurRate"
    t.float "CessRate"
    t.float "HscRate"
    t.float "TdsBAmt"
    t.float "TdsBAmtSC"
    t.float "TdsBAmtFC"
    t.float "SurBAmt"
    t.float "SurBAmtSC"
    t.float "SurBAmtFC"
    t.float "CessBAmt"
    t.float "CessBAmtSC"
    t.float "CessBAmtFC"
    t.float "HscBAmt"
    t.float "HscBAmtSC"
    t.float "HscBAmtFC"
    t.float "TdsAmnt"
    t.float "TdsAmntSC"
    t.float "TdsAmntFC"
    t.float "SurAmnt"
    t.float "SurAmntSC"
    t.float "SurAmntFC"
    t.float "CessAmnt"
    t.float "CessAmntSC"
    t.float "CessAmntFC"
    t.float "HscAmnt"
    t.float "HscAmntSC"
    t.float "HscAmntFC"
    t.float "TdsAppl"
    t.float "TdsApplSC"
    t.float "TdsApplFC"
    t.float "SurAppl"
    t.float "SurApplSC"
    t.float "SurApplFC"
    t.float "CessAppl"
    t.float "CessApplSC"
    t.float "CessApplFC"
    t.float "HscAppl"
    t.float "HscApplSC"
    t.float "HscApplFC"
    t.integer "BatchNum"
    t.string "InCSTCode"
    t.string "OutCSTCode"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "ojdts", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
    t.integer "BatchNum"
    t.integer "TransId"
    t.string "BtfStatus"
    t.string "TransType"
    t.string "BaseRef"
    t.date "RefDate"
    t.string "Memo"
    t.string "Ref1"
    t.string "Ref2"
    t.integer "CreatedBy"
    t.float "LocTotal"
    t.float "FcTotal"
    t.float "SysTotal"
    t.string "TransCode"
    t.string "OrignCurr"
    t.float "TransRate"
    t.integer "BtfLine"
    t.string "TransCurr"
    t.string "Project"
    t.date "DueDate"
    t.date "TaxDate"
    t.string "PCAddition"
    t.integer "FinncPriod"
    t.string "DataSource"
    t.date "UpdateDate"
    t.date "CreateDate"
    t.integer "UserSign"
    t.integer "UserSign2"
    t.string "RefndRprt"
    t.integer "LogInstanc"
    t.string "ObjType"
    t.string "Indicator"
    t.string "AdjTran"
    t.string "RevSource"
    t.date "StornoDate"
    t.integer "StornoToTr"
    t.string "AutoStorno"
    t.string "Corisptivi"
    t.date "VatDate"
    t.string "StampTax"
    t.integer "Series"
    t.integer "Number"
    t.string "AutoVAT"
    t.integer "DocSeries"
    t.string "FolioPref"
    t.integer "FolioNum"
    t.integer "CreateTime"
    t.string "BlockDunn"
    t.string "ReportEU"
    t.string "Report347"
    t.string "Printed"
    t.string "DocType"
    t.integer "AttNum"
    t.string "GenRegNo"
    t.integer "RG23APart2"
    t.integer "RG23CPart2"
    t.integer "MatType"
    t.string "Creator"
    t.string "Approver"
    t.integer "Location"
    t.integer "SeqCode"
    t.integer "Serial"
    t.string "SeriesStr"
    t.string "SubStr"
    t.string "AutoWT"
    t.float "WTSum"
    t.float "WTSumSC"
    t.float "WTSumFC"
    t.float "WTApplied"
    t.float "WTAppliedS"
    t.float "WTAppliedF"
    t.float "BaseAmnt"
    t.float "BaseAmntSC"
    t.float "BaseAmntFC"
    t.float "BaseVtAt"
    t.float "BaseVtAtSC"
    t.float "BaseVtAtFC"
    t.string "VersionNum"
    t.integer "BaseTrans"
    t.string "ResidenNum"
    t.string "OperatCode"
    t.string "Ref3"
    t.string "SSIExmpt"
    t.text "SignMsg"
    t.text "SignDigest"
    t.string "CertifNum"
    t.integer "KeyVersion"
    t.integer "CUP"
    t.integer "CIG"
    t.string "SupplCode"
    t.integer "SPSrcType"
    t.integer "SPSrcID"
    t.integer "SPSrcDLN"
    t.string "DeferedTax"
    t.integer "AgrNo"
    t.integer "SeqNum"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "ttts", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
